# HOPE NPCs - Agent Context
# Part of the SpiralSafe Ecosystem
# Version: 2.1.0
# Format: SpiralSafe .context.yaml

domain: hope-npcs
version: "2.1.0"
type: minecraft-server-framework

description: |
  HOPE NPCs (Human-Operated Personality Engines) - AI-powered Minecraft NPCs
  that transform game NPCs into intelligent conversational partners.
  Part of the SpiralSafe Ecosystem for human-AI collaboration.
  Built with SAIF methodology for modular, maintainable deployment.

architecture:
  pattern: modular-orchestrator
  components:
    orchestrator: setup/INSTALL.ps1
    core_modules:
      - setup/core/Display.psm1   # UI/Display functions
      - setup/core/Logger.psm1    # Logging system
      - setup/core/Safety.psm1    # Validation & backups
      - setup/core/Config.psm1    # Configuration management
    phases:
      - setup/phases/01-Preflight.ps1   # Prerequisites check
      - setup/phases/02-Java.ps1        # Java installation
      - setup/phases/03-PaperMC.ps1     # Server installation
      - setup/phases/04-Plugins.ps1     # Plugin installation
      - setup/phases/05-Configure.ps1   # Final configuration
    plugin:
      path: ClaudeNPC/
      type: java-maven
      main_class: com.claudenpc.ClaudeNPC
      dependencies:
        - PaperMC API 1.21.3
        - Citizens 2.0.36
        - OkHttp 4.12.0
        - Gson 2.10.1

key_files:
  entry_point: INSTALL.ps1
  main_readme: README.md
  test_runner: test-core-modules.ps1
  plugin_config: ClaudeNPC/pom.xml

commands:
  install: "powershell -ExecutionPolicy Bypass -File INSTALL.ps1"
  test: "powershell -NoProfile -ExecutionPolicy Bypass -File test-core-modules.ps1"
  build_plugin: "cd ClaudeNPC && mvn clean package"

integrations:
  spiralsafe:
    api_base: https://api.spiralsafe.org
    endpoints:
      wave: /api/wave/analyze
      bump: /api/bump/create
      awi: /api/awi/request
      atom: /api/atom/create
      context: /api/context/store
      health: /api/health
  claude_api:
    purpose: NPC dialogue generation
    requires: ANTHROPIC_API_KEY

signals:
  use_when:
    - minecraft_server_setup
    - ai_npc_implementation
    - papermc_plugin_development
    - spiralsafe_integration
  avoid_when:
    - bedrock_edition
    - vanilla_server_only
    - non_windows_primary

invariants:
  - PowerShell 5.1+ required
  - Java 21+ required for plugin
  - Windows environment assumed
  - Administrator privileges needed for INSTALL.ps1

relationships:
  part_of:
    - SpiralSafe Ecosystem
  depends_on:
    - SpiralSafe core
    - Citizens plugin
    - PaperMC server
  sibling_repos:
    - https://github.com/toolate28/SpiralSafe
    - https://github.com/toolate28/wave-toolkit
    - https://github.com/toolate28/kenl
    - https://github.com/toolate28/quantum-redstone
  consumed_by:
    - minecraft_players
    - server_administrators

meta:
  source: Hope&&Sauced
  methodology: SAIF
  confidence: high
  last_updated: "2026-01-09"
  ecosystem_url: "https://github.com/toolate28/SpiralSafe"
